/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PRINTER_HEADER
#define PRINTER_HEADER

#include "Absyn.h"

/* Certain applications may improve performance by changing the buffer size */
#define BUFFER_INITIAL 2048
/* You may wish to change _L_PAREN or _R_PAREN */
#define _L_PAREN '('
#define _R_PAREN ')'

/* The following are simple heuristics for rendering terminals */
/* You may wish to change them */
void renderCC(Char c);
void renderCS(String s);
void indent(void);
void backup(void);
void onEmptyLine(void);
void removeTrailingSpaces(void);
void removeTrailingWhitespace(void);


char *printExpression(Expression p);
char *printList(List p);
char *printBang(Bang p);
char *printSubshell(Subshell p);
char *printArgs(Args p);
char *printListIdent(ListIdent p);

void ppExpression(Expression p, int i);
void ppList(List p, int i);
void ppBang(Bang p, int i);
void ppSubshell(Subshell p, int i);
void ppArgs(Args p, int i);
void ppListIdent(ListIdent p, int i);

char *showExpression(Expression p);
char *showList(List p);
char *showBang(Bang p);
char *showSubshell(Subshell p);
char *showArgs(Args p);
char *showListIdent(ListIdent p);

void shExpression(Expression p);
void shList(List p);
void shBang(Bang p);
void shSubshell(Subshell p);
void shArgs(Args p);
void shListIdent(ListIdent p);

void ppInteger(Integer n, int i);
void ppDouble(Double d, int i);
void ppChar(Char c, int i);
void ppString(String s, int i);
void ppIdent(String s, int i);
void shInteger(Integer n);
void shDouble(Double d);
void shChar(Char c);
void shString(String s);
void shIdent(String s);
void bufEscapeS(const char *s);
void bufEscapeC(const char c);
void bufAppendS(const char *s);
void bufAppendC(const char c);
void bufReset(void);
void resizeBuffer(void);

#endif

