/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printExpression(Expression p)
{
  _n_ = 0;
  bufReset();
  ppExpression(p, 0);
  return buf_;
}
char *printList(List p)
{
  _n_ = 0;
  bufReset();
  ppList(p, 0);
  return buf_;
}
char *printBang(Bang p)
{
  _n_ = 0;
  bufReset();
  ppBang(p, 0);
  return buf_;
}
char *printSubshell(Subshell p)
{
  _n_ = 0;
  bufReset();
  ppSubshell(p, 0);
  return buf_;
}
char *printArgs(Args p)
{
  _n_ = 0;
  bufReset();
  ppArgs(p, 0);
  return buf_;
}
char *printListIdent(ListIdent p)
{
  _n_ = 0;
  bufReset();
  ppListIdent(p, 0);
  return buf_;
}
char *showExpression(Expression p)
{
  _n_ = 0;
  bufReset();
  shExpression(p);
  return buf_;
}
char *showList(List p)
{
  _n_ = 0;
  bufReset();
  shList(p);
  return buf_;
}
char *showBang(Bang p)
{
  _n_ = 0;
  bufReset();
  shBang(p);
  return buf_;
}
char *showSubshell(Subshell p)
{
  _n_ = 0;
  bufReset();
  shSubshell(p);
  return buf_;
}
char *showArgs(Args p)
{
  _n_ = 0;
  bufReset();
  shArgs(p);
  return buf_;
}
char *showListIdent(ListIdent p)
{
  _n_ = 0;
  bufReset();
  shListIdent(p);
  return buf_;
}
void ppExpression(Expression p, int _i_)
{
  switch(p->kind)
  {
  case is_ExpressionList:
    if (_i_ > 0) renderC(_L_PAREN);
    ppList(p->u.expressionlist_.list_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Expression!\n");
    exit(1);
  }
}

void ppList(List p, int _i_)
{
  switch(p->kind)
  {
  case is_List1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBang(p->u.list1_.bang_, 0);
    renderC(';');
    ppList(p->u.list1_.list_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_List2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBang(p->u.list2_.bang_, 0);
    renderS("||");
    ppList(p->u.list2_.list_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_List3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppBang(p->u.list3_.bang_, 0);
    renderS("&&");
    ppList(p->u.list3_.list_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing List!\n");
    exit(1);
  }
}

void ppBang(Bang p, int _i_)
{
  switch(p->kind)
  {
  case is_Bang1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('!');
    ppSubshell(p->u.bang1_.subshell_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_BangSubshell:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSubshell(p->u.bangsubshell_.subshell_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Bang!\n");
    exit(1);
  }
}

void ppSubshell(Subshell p, int _i_)
{
  switch(p->kind)
  {
  case is_Subshell1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('(');
    ppList(p->u.subshell1_.list_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Subshell2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.subshell2_.ident_, 0);
    ppArgs(p->u.subshell2_.args_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Subshell!\n");
    exit(1);
  }
}

void ppArgs(Args p, int _i_)
{
  switch(p->kind)
  {
  case is_Args1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("$(");
    ppExpression(p->u.args1_.expression_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Args2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppListIdent(p->u.args2_.listident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Args!\n");
    exit(1);
  }
}

void ppListIdent(ListIdent listident, int i)
{
  if (listident == 0)
  { /* nil */
  }
  else
  { /* cons */
    ppIdent(listident->ident_, 0);
    renderC(' ');
    ppListIdent(listident->listident_, 0);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shExpression(Expression p)
{
  switch(p->kind)
  {
  case is_ExpressionList:
    bufAppendC('(');

    bufAppendS("ExpressionList");

    bufAppendC(' ');

    shList(p->u.expressionlist_.list_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Expression!\n");
    exit(1);
  }
}

void shList(List p)
{
  switch(p->kind)
  {
  case is_List1:
    bufAppendC('(');

    bufAppendS("List1");

    bufAppendC(' ');

    shBang(p->u.list1_.bang_);
  bufAppendC(' ');
    shList(p->u.list1_.list_);

    bufAppendC(')');

    break;
  case is_List2:
    bufAppendC('(');

    bufAppendS("List2");

    bufAppendC(' ');

    shBang(p->u.list2_.bang_);
  bufAppendC(' ');
    shList(p->u.list2_.list_);

    bufAppendC(')');

    break;
  case is_List3:
    bufAppendC('(');

    bufAppendS("List3");

    bufAppendC(' ');

    shBang(p->u.list3_.bang_);
  bufAppendC(' ');
    shList(p->u.list3_.list_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing List!\n");
    exit(1);
  }
}

void shBang(Bang p)
{
  switch(p->kind)
  {
  case is_Bang1:
    bufAppendC('(');

    bufAppendS("Bang1");

    bufAppendC(' ');

    shSubshell(p->u.bang1_.subshell_);

    bufAppendC(')');

    break;
  case is_BangSubshell:
    bufAppendC('(');

    bufAppendS("BangSubshell");

    bufAppendC(' ');

    shSubshell(p->u.bangsubshell_.subshell_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Bang!\n");
    exit(1);
  }
}

void shSubshell(Subshell p)
{
  switch(p->kind)
  {
  case is_Subshell1:
    bufAppendC('(');

    bufAppendS("Subshell1");

    bufAppendC(' ');

    shList(p->u.subshell1_.list_);

    bufAppendC(')');

    break;
  case is_Subshell2:
    bufAppendC('(');

    bufAppendS("Subshell2");

    bufAppendC(' ');

    shIdent(p->u.subshell2_.ident_);
  bufAppendC(' ');
    shArgs(p->u.subshell2_.args_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Subshell!\n");
    exit(1);
  }
}

void shArgs(Args p)
{
  switch(p->kind)
  {
  case is_Args1:
    bufAppendC('(');

    bufAppendS("Args1");

    bufAppendC(' ');

    shExpression(p->u.args1_.expression_);

    bufAppendC(')');

    break;
  case is_Args2:
    bufAppendC('(');

    bufAppendS("Args2");

    bufAppendC(' ');

    shListIdent(p->u.args2_.listident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Args!\n");
    exit(1);
  }
}

void shListIdent(ListIdent listident)
{
  bufAppendC('[');
  while(listident != 0)
  {
    if (listident->listident_)
    {
      shIdent(listident->ident_);
      bufAppendS(", ");
      listident = listident->listident_;
    }
    else
    {
      shIdent(listident->ident_);
      listident = 0;
    }
  }
  bufAppendC(']');
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

