/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitExpression(Expression p);
void visitList(List p);
void visitBang(Bang p);
void visitSubshell(Subshell p);
void visitArgs(Args p);
void visitListIdent(ListIdent p);


void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

